name: Maven Allure Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean test

      - name: Generate Allure report
        run: |
          sudo apt-get install -y unzip curl
          curl -sL https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.zip -o allure.zip
          unzip allure.zip -d allure
          allure/bin/allure generate target/allure-results --clean -o target/allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-r
